// <auto-generated />
namespace Uracadex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdSNARSUniversiy_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdSNARSUniversiy_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "202009212233411_AdSNARSUniversiy_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
